# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profitable-vertical-app"
client_id = "0c428680c6513d61ce0193be075966ec"
application_url = "https://determines-landscape-genius-fast.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content"

[auth]
redirect_urls = [
  "https://determines-landscape-genius-fast.trycloudflare.com/auth/callback",
  "https://determines-landscape-genius-fast.trycloudflare.com/auth/shopify/callback",
  "https://determines-landscape-genius-fast.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quick-start-7124c8bf.myshopify.com"
